name: Orchestrator Build

on:
  workflow_dispatch:
  push:
    paths:
      - .github/workflows/Orchestrator_Build.yml
  pull_request:
    paths:
      - ProcessorOrchestrator/**

jobs:
  orchestrator_build:
    name: Orchestrator Build
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v1
        with:
          submodules: recursive
      - name: Build
        run: docker-compose -f ./ProcessorOrchestrator/docker-compose.yml build --no-cache
      - name: Remove
        run: docker-compose -f ./ProcessorOrchestrator/docker-compose.yml down --rmi all
        if: ${{ always() }}
      - name: Prune images
        run: docker image prune --force --filter "until=24h"
        if: ${{ always() }}
